name: main

permissions:
  contents: write

on:

  push:
    branches: [ main, fix-windows-dll ]
    tags: [ "*" ]
    paths-ignore: [ "*.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build-test-package:
    name: Build/Release Packages
    uses: ./.github/workflows/build.yml
